version: "3.8"

services:
  # Redis service
  redis:
    image: redis:latest
    container_name: soft-talks-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      - softtalks-network

  # Node.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soft-talks-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - NODE_ENV=production
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - softtalks-network

# Define network
networks:
  softtalks-network:
    driver: bridge
